#!/usr/bin/env bash
#
# Setup script for self-hosted Supabase
# Generates all required secrets and creates .env files
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUPABASE_DIR="$(dirname "$SCRIPT_DIR")"
PROJECT_ROOT="$(dirname "$(dirname "$SUPABASE_DIR")")"
FRONTEND_DIR="$PROJECT_ROOT/onlypawsfrontend"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step() { echo -e "${CYAN}[STEP]${NC} $1"; }

# Check for required tools
check_requirements() {
    local missing=()

    if ! command -v openssl &> /dev/null; then
        missing+=("openssl")
    fi

    if [ ${#missing[@]} -ne 0 ]; then
        log_error "Missing required tools: ${missing[*]}"
        exit 1
    fi
}

# Base64 URL encode (no padding)
base64url_encode() {
    openssl base64 -e -A | tr '+/' '-_' | tr -d '='
}

# Create JWT token
create_jwt() {
    local secret="$1"
    local role="$2"
    local exp="$3"

    local header='{"alg":"HS256","typ":"JWT"}'
    local header_base64=$(echo -n "$header" | base64url_encode)

    local payload="{\"iss\":\"supabase\",\"role\":\"${role}\",\"iat\":$(date +%s),\"exp\":${exp}}"
    local payload_base64=$(echo -n "$payload" | base64url_encode)

    local signature=$(echo -n "${header_base64}.${payload_base64}" | openssl dgst -sha256 -hmac "$secret" -binary | base64url_encode)

    echo "${header_base64}.${payload_base64}.${signature}"
}

# Generate random string (URL-safe, no special chars)
generate_secret() {
    local length="${1:-32}"
    openssl rand -hex "$length" | tr -d '\n'
}

# Main setup
main() {
    echo ""
    echo -e "${BLUE}╔════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║     Supabase Self-Hosting Setup Script     ║${NC}"
    echo -e "${BLUE}╚════════════════════════════════════════════╝${NC}"
    echo ""

    check_requirements

    # Check if .env already exists
    if [ -f "$SUPABASE_DIR/.env" ]; then
        echo -e "${YELLOW}Existing .env file found at:${NC}"
        echo "  $SUPABASE_DIR/.env"
        echo ""
        read -p "Overwrite? (y/N) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            log_info "Keeping existing configuration"
            exit 0
        fi
    fi

    log_step "Generating secrets..."

    # Generate secrets
    POSTGRES_PASSWORD=$(generate_secret 24)
    JWT_SECRET=$(generate_secret 32)
    SECRET_KEY_BASE=$(generate_secret 64)

    log_info "Generated POSTGRES_PASSWORD"
    log_info "Generated JWT_SECRET"
    log_info "Generated SECRET_KEY_BASE"

    log_step "Generating JWT keys..."

    # Expiry: 10 years from now
    EXPIRY=$(($(date +%s) + 315360000))

    ANON_KEY=$(create_jwt "$JWT_SECRET" "anon" "$EXPIRY")
    SERVICE_ROLE_KEY=$(create_jwt "$JWT_SECRET" "service_role" "$EXPIRY")

    log_info "Generated ANON_KEY"
    log_info "Generated SERVICE_ROLE_KEY"

    log_step "Creating Supabase .env file..."

    # Create Supabase .env
    cat > "$SUPABASE_DIR/.env" << EOF
############
# Secrets - Auto-generated by setup.sh
# Generated on: $(date -Iseconds)
############

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
JWT_SECRET=${JWT_SECRET}
SECRET_KEY_BASE=${SECRET_KEY_BASE}
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}

############
# Database
############

POSTGRES_DB=postgres
POSTGRES_PORT=5432

############
# API Configuration
############

API_EXTERNAL_URL=http://localhost:8000
SITE_URL=http://localhost:3000
ADDITIONAL_REDIRECT_URLS=

############
# Auth Configuration
############

DISABLE_SIGNUP=false
ENABLE_EMAIL_AUTOCONFIRM=true
ENABLE_ANONYMOUS_USERS=false
ENABLE_EMAIL_SIGNUP=true
JWT_EXP=3600
RATE_LIMIT_EMAIL_SENT=100

############
# SMTP Configuration (optional)
############

SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_ADMIN_EMAIL=
SMTP_SENDER_NAME=

############
# Studio Configuration
############

STUDIO_PORT=3001
STUDIO_DEFAULT_ORGANIZATION=Default Organization
STUDIO_DEFAULT_PROJECT=Default Project

############
# Kong API Gateway Ports
############

KONG_HTTP_PORT=8000
KONG_HTTPS_PORT=8443

############
# Optional Features
############

ENABLE_LOGS=true
LOGFLARE_API_KEY=
PGRST_DB_SCHEMAS=public,storage,graphql_public
IMGPROXY_ENABLE_WEBP_DETECTION=true
EOF

    log_info "Created $SUPABASE_DIR/.env"

    # Create frontend .env
    log_step "Creating frontend .env file..."

    if [ -d "$FRONTEND_DIR" ]; then
        cat > "$FRONTEND_DIR/.env" << EOF
# Supabase Configuration
# Auto-generated by containers/supabase/scripts/setup.sh
# Generated on: $(date -Iseconds)

# Self-hosted Supabase (local containers)
NEXT_PUBLIC_SUPABASE_URL=http://localhost:8000
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${ANON_KEY}
EOF
        log_info "Created $FRONTEND_DIR/.env"
    else
        log_warn "Frontend directory not found at $FRONTEND_DIR"
        log_info "Frontend .env content:"
        echo ""
        echo "NEXT_PUBLIC_SUPABASE_URL=http://localhost:8000"
        echo "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${ANON_KEY}"
        echo ""
    fi

    # Summary
    echo ""
    echo -e "${GREEN}╔════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║            Setup Complete!                 ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════════╝${NC}"
    echo ""
    echo "Files created:"
    echo "  - $SUPABASE_DIR/.env"
    [ -d "$FRONTEND_DIR" ] && echo "  - $FRONTEND_DIR/.env"
    echo ""
    echo "Next steps:"
    echo "  1. Start Supabase:  cd $SUPABASE_DIR && ./start.sh"
    echo "  2. Start frontend:  cd $FRONTEND_DIR && npm run dev"
    echo ""
    echo "Access points:"
    echo "  - API Gateway:  http://localhost:8000"
    echo "  - Studio:       http://localhost:3001"
    echo "  - Frontend:     http://localhost:3000"
    echo ""
}

main "$@"
